export const videosList = [												
  {title:"What is The Matrix?", link:"https://www.youtube.com/watch?v=Td_ieom1g88", subtitle:"This is where I'm coming from",host:"Morpheous", guest: "Neo", duration: "3 minutes"},
  {title:"What is money?", link:"https://www.youtube.com/watch?v=J4IylYhh6Vw", subtitle:"Crash course on money",host:"Robert Breedlove", guest: "null", duration: "8 minutes"},
  {title:"Bitcoin Fixes Everything", link:"https://www.youtube.com/watch?v=gvnsSXq6UAI", subtitle:"Every institution is build on top of this global credit mess",host:"Anthony Pompliano", guest: "Jeff Booth", duration: "55 minutes"},
  {title:"What is a CDO (and a CDS?)", link:"https://www.youtube.com/watch?v=xbiDrzTd8fE", subtitle:"And the best part is they're eating 3 day old halibut",host:"null", guest: "null", duration: "10 minutes"},
  {title:"Michael Burry Vanderbilt lecture 11 years ago", link:"https://www.youtube.com/watch?v=fx2ClTpnAAs", subtitle:"null",host:"Michael Burry", guest: "null", duration: "35 minutes"},
  {title:"Authoritarianism", link:"https://www.youtube.com/watch?v=kSbMU5CbFM0", subtitle:"A human trying to save other humans from themselves and others",host:"Lex Friedman", guest: "Alex Gladstein", duration: ">2+ hours"},
  {title:"Core Values", link:"https://www.youtube.com/watch?v=mDyBbGCiBUU", subtitle:"A war on block size",host:"Lex Friedman", guest: "Nic Carter", duration: ">2+ hours"},
  {title:"I'm also curious as an outsider'", link:"https://www.youtube.com/watch?v=FXvQcuIb5rU", subtitle:"Saifedean Ammous",host:"Jordan Peterson", guest: "Saifedean Ammous", duration: ">1+ hours"},
  {title:"Austrian Economics", link:"https://www.youtube.com/watch?v=gp4U5aH_T6A", subtitle:"Author of The Bitcoin Standard and The Fiat Standard",host:"Lex Friedman", guest: "Saifedean Ammous", duration: ">4+ hours"},
  {title:"Spaceforce's BTC insider", link:"https://www.youtube.com/watch?v=wRxc7uUqAyE", subtitle:"Jason Lowery from MIT and Spaceforce",host:"Robert Breedlove", guest: "Jason Lowery", duration: ">2+ hours"},
  {title:"Bitcoin’s Killer App", link:"https://youtu.be/B1PI7BCjopk", subtitle:"",host:"", guest: "Michael Saylor", duration: "1.2"},
  {title:"The UnCommunist Manifesto", link:"https://bitcoinmagazine.com/culture/bitcoin-independence-and-uncommunism", subtitle:"Bitcoin Magazine",host:"", guest: "", duration: ""},
  {title:"Everything you know about the Economy is wrong", link:"https://youtu.be/KNa-fewraJA", subtitle:"",host:"What Bitcoin Did", guest: "Jeff Snider", duration: "1.5"},
  {title:"A look at lightning", link:"https://www.swanbitcoin.com/a-look-at-the-lightning-network/", subtitle:"",host:"Lyn Alden", guest: "", duration: ""},
  {title:"Economy basics", link:"https://youtu.be/PHe0bXAIuk0", subtitle:"",host:"Ray Dalio", guest: "", duration: ""},
  {title:"What is ACID inflation", link:"https://youtu.be/PR9A3Oyvo5E", subtitle:"",host:"Anthony Pompliano", guest: "Michael Saylor", duration: "10"},
]												